import fs from 'node:fs';
import path from 'node:path';

// Mirrors a project's timeline, issues, and notes into `<repo>/.gate/` so they
// live in the same repository as the code they describe. Nothing here runs git
// commands — the files are just tracked/committed/pushed through the user's own
// workflow, same as any other file in the tree (see AGENTS.md: no integration
// command, no automation of push/merge).
const RELEVANT_PREFIXES = ['project.', 'timeline.', 'issue.', 'note.', 'feature.', 'planning.', 'milestone.'];

// .gate/ holds this machine's view of a project (timeline, issues, notes). It
// stays out of the project's own commits by default, so cloning someone's repo
// never silently exposes their local Gate state. This only edits .gitignore —
// it never runs git itself.
export function ensureGateIgnored(repoPath) {
  const gitignorePath = path.join(repoPath, '.gitignore');
  const existing = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf8') : '';
  const alreadyIgnored = existing
    .split('\n')
    .some((line) => line.trim() === '.gate/' || line.trim() === '.gate');
  if (alreadyIgnored) return;
  const prefix = existing && !existing.endsWith('\n') ? '\n\n' : existing ? '\n' : '';
  fs.writeFileSync(gitignorePath, `${existing}${prefix}# Gate local project state (not shared by default)\n.gate/\n`);
}

function statusChar(status) {
  return ({
    planned: ' ', ready: '>', running: '~', blocked: '!', review: '?',
    approved: 'A', complete: 'x', rejected: 'x', failed: 'x', cancelled: '-'
  })[status] || ' ';
}

export class RepoMirrorService {
  constructor({ db, projects }) {
    this.db = db;
    this.projects = projects;
  }

  attach(eventStore) {
    return eventStore.subscribeAll((event) => {
      if (!RELEVANT_PREFIXES.some((prefix) => event.type.startsWith(prefix))) return;
      try {
        this.sync(event.projectId);
      } catch {
        // Best-effort convenience view; never let a mirror write break the command that triggered it.
      }
    });
  }

  sync(projectId) {
    const project = this.projects.get(projectId);
    const dir = path.join(project.repoPath, '.gate');
    // Repairs projects connected before ensureGateIgnored existed at connect-time.
    // Safe to call on every sync: GitAdapter's dirty check exempts a .gitignore
    // change when it is exactly this appended block and nothing else.
    ensureGateIgnored(project.repoPath);
    fs.mkdirSync(dir, { recursive: true });

    const nodes = this.db.prepare('SELECT * FROM timeline_nodes WHERE project_id = ? ORDER BY ordinal, id').all(projectId);
    const edges = this.db.prepare('SELECT * FROM timeline_edges WHERE project_id = ? ORDER BY id').all(projectId);
    const gates = this.db.prepare('SELECT * FROM gates WHERE project_id = ? ORDER BY id').all(projectId);
    const issues = this.db.prepare('SELECT * FROM issues WHERE project_id = ? ORDER BY id').all(projectId);
    const notes = this.db.prepare('SELECT * FROM notes WHERE project_id = ? ORDER BY id').all(projectId);
    const features = this.db.prepare('SELECT * FROM features WHERE project_id = ? ORDER BY created_at, id').all(projectId).map((feature) => ({
      ...feature,
      planningRequests: this.db.prepare("SELECT id, status, timeline_draft_id, created_at, accepted_at FROM planning_requests WHERE project_id = ? AND source_type = 'feature' AND source_id = ? ORDER BY created_at").all(projectId, feature.id)
    }));
    const milestones = nodes.filter((node) => node.kind === 'milestone');
    const steps = nodes.filter((node) => node.kind === 'step');

    this.#writeJson(path.join(dir, 'project.json'), {
      gateProjectId: project.id,
      name: project.name,
      baseBranch: project.baseBranch,
      interactionLevel: project.interactionLevel,
      providerKind: project.providerKind
    });
    this.#writeJson(path.join(dir, 'timeline.json'), { generatedAt: new Date().toISOString(), nodes, edges, gates });
    this.#writeJson(path.join(dir, 'issues.json'), issues);
    this.#writeJson(path.join(dir, 'notes.json'), notes);
    this.#writeJson(path.join(dir, 'features.json'), features);
    this.#writeText(path.join(dir, 'MILESTONES.md'), this.#renderMilestones(milestones, steps, edges, gates));
    this.#writeText(path.join(dir, 'ISSUES.md'), this.#renderIssues(issues, notes));
  }

  #renderMilestones(milestones, steps, edges, gates) {
    const gatesByNode = (nodeId) => gates.filter((gate) => gate.node_id === nodeId);
    const gatesInto = (nodeId) => edges
      .filter((edge) => edge.to_node_id === nodeId && edge.type !== 'depends_on')
      .map((edge) => milestones.find((m) => m.id === edge.from_node_id) || steps.find((s) => s.id === edge.from_node_id))
      .filter(Boolean);
    const lines = ['# Milestones', '', '_Generated by Gate. Edit through the app, not this file — it is overwritten on every change._', ''];
    for (const milestone of milestones) {
      const children = steps.filter((step) => step.parent_id === milestone.id);
      const done = children.filter((step) => step.status === 'complete').length;
      lines.push(`## [${statusChar(milestone.status)}] ${milestone.display_key || milestone.id} — ${milestone.title} (${done}/${children.length})`);
      const gatedBy = gatesInto(milestone.id);
      if (gatedBy.length) {
        lines.push(`Gated by: ${gatedBy.map((node) => node.display_key || node.title).join(', ')}`);
      }
      for (const step of children) {
        const stepGates = gatesByNode(step.id).map((gate) => `${gate.type}:${gate.status}`).join(', ');
        lines.push(`- [${statusChar(step.status)}] ${step.display_key || step.id} ${step.title}${stepGates ? ` (${stepGates})` : ''}`);
      }
      lines.push('');
    }
    return lines.join('\n');
  }

  #renderIssues(issues, notes) {
    const lines = ['# Issues', '', '_Generated by Gate. Edit through the app, not this file — it is overwritten on every change._', ''];
    for (const status of ['open', 'in_progress', 'closed']) {
      const group = issues.filter((issue) => issue.status === status);
      if (!group.length) continue;
      lines.push(`## ${status}`);
      for (const issue of group) lines.push(`- #${issue.id} ${issue.title}${issue.branch ? ` (${issue.branch})` : ''}`);
      lines.push('');
    }
    if (notes.length) {
      lines.push('## Notes');
      for (const note of notes) lines.push(`- ${note.body}`);
      lines.push('');
    }
    return lines.join('\n');
  }

  #writeJson(filePath, value) {
    fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
  }

  #writeText(filePath, text) {
    fs.writeFileSync(filePath, text);
  }
}
